# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'otoklim_dialog_base.ui'
#
# Created: Tue Jul 11 11:21:03 2017
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_OtoklimDialogBase(object):
    def setupUi(self, OtoklimDialogBase):
        OtoklimDialogBase.setObjectName(_fromUtf8("OtoklimDialogBase"))
        OtoklimDialogBase.resize(594, 565)
        self.verticalLayout = QtGui.QVBoxLayout(OtoklimDialogBase)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.frame_main = QtGui.QFrame(OtoklimDialogBase)
        self.frame_main.setFrameShape(QtGui.QFrame.Box)
        self.frame_main.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_main.setObjectName(_fromUtf8("frame_main"))
        self.gridLayout_9 = QtGui.QGridLayout(self.frame_main)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.groupBox_1 = QtGui.QGroupBox(self.frame_main)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_1.setFont(font)
        self.groupBox_1.setAutoFillBackground(False)
        self.groupBox_1.setFlat(False)
        self.groupBox_1.setObjectName(_fromUtf8("groupBox_1"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.Delimiter = QtGui.QLineEdit(self.groupBox_1)
        self.Delimiter.setMaximumSize(QtCore.QSize(25, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Delimiter.setFont(font)
        self.Delimiter.setText(_fromUtf8(""))
        self.Delimiter.setMaxLength(1)
        self.Delimiter.setDragEnabled(True)
        self.Delimiter.setObjectName(_fromUtf8("Delimiter"))
        self.gridLayout.addWidget(self.Delimiter, 1, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 3, 3, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.mode_1 = QtGui.QRadioButton(self.groupBox_1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.mode_1.setFont(font)
        self.mode_1.setChecked(True)
        self.mode_1.setObjectName(_fromUtf8("mode_1"))
        self.gridLayout.addWidget(self.mode_1, 6, 0, 1, 2)
        self.label_2 = QtGui.QLabel(self.groupBox_1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.mode_2 = QtGui.QRadioButton(self.groupBox_1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.mode_2.setFont(font)
        self.mode_2.setObjectName(_fromUtf8("mode_2"))
        self.gridLayout.addWidget(self.mode_2, 7, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.mode_3 = QtGui.QRadioButton(self.groupBox_1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.mode_3.setFont(font)
        self.mode_3.setObjectName(_fromUtf8("mode_3"))
        self.gridLayout.addWidget(self.mode_3, 8, 0, 1, 1)
        self.Year = QtGui.QLineEdit(self.groupBox_1)
        self.Year.setMaximumSize(QtCore.QSize(65, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Year.setFont(font)
        self.Year.setText(_fromUtf8(""))
        self.Year.setMaxLength(4)
        self.Year.setDragEnabled(True)
        self.Year.setObjectName(_fromUtf8("Year"))
        self.gridLayout.addWidget(self.Year, 3, 1, 1, 2)
        self.line = QtGui.QFrame(self.groupBox_1)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 4, 0, 1, 5)
        self.label_7 = QtGui.QLabel(self.groupBox_1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 1, 2, 1, 2)
        self.label_3 = QtGui.QLabel(self.groupBox_1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.mode_4 = QtGui.QRadioButton(self.groupBox_1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.mode_4.setFont(font)
        self.mode_4.setObjectName(_fromUtf8("mode_4"))
        self.gridLayout.addWidget(self.mode_4, 9, 0, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.Input_CH_CSV = QtGui.QLineEdit(self.groupBox_1)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Input_CH_CSV.setFont(font)
        self.Input_CH_CSV.setMaxLength(62767)
        self.Input_CH_CSV.setDragEnabled(True)
        self.Input_CH_CSV.setObjectName(_fromUtf8("Input_CH_CSV"))
        self.gridLayout.addWidget(self.Input_CH_CSV, 0, 1, 1, 3)
        self.Browse_CH_CSV = QtGui.QPushButton(self.groupBox_1)
        self.Browse_CH_CSV.setMaximumSize(QtCore.QSize(60, 25))
        self.Browse_CH_CSV.setObjectName(_fromUtf8("Browse_CH_CSV"))
        self.gridLayout.addWidget(self.Browse_CH_CSV, 0, 4, 1, 1)
        self.Select_Months = QtGui.QComboBox(self.groupBox_1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Select_Months.setFont(font)
        self.Select_Months.setObjectName(_fromUtf8("Select_Months"))
        self.Select_Months.addItem(_fromUtf8(""))
        self.Select_Months.addItem(_fromUtf8(""))
        self.Select_Months.addItem(_fromUtf8(""))
        self.Select_Months.addItem(_fromUtf8(""))
        self.Select_Months.addItem(_fromUtf8(""))
        self.Select_Months.addItem(_fromUtf8(""))
        self.Select_Months.addItem(_fromUtf8(""))
        self.Select_Months.addItem(_fromUtf8(""))
        self.Select_Months.addItem(_fromUtf8(""))
        self.Select_Months.addItem(_fromUtf8(""))
        self.Select_Months.addItem(_fromUtf8(""))
        self.Select_Months.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.Select_Months, 2, 1, 1, 3)
        self.gridLayout_9.addWidget(self.groupBox_1, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_main)
        self.frame_optional = QtGui.QFrame(OtoklimDialogBase)
        self.frame_optional.setEnabled(False)
        self.frame_optional.setFrameShape(QtGui.QFrame.Box)
        self.frame_optional.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_optional.setObjectName(_fromUtf8("frame_optional"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame_optional)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.listWidget_option = QtGui.QListWidget(self.frame_optional)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Tahoma"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.listWidget_option.setFont(font)
        self.listWidget_option.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.listWidget_option.setObjectName(_fromUtf8("listWidget_option"))
        self.horizontalLayout.addWidget(self.listWidget_option)
        self.widget = QtGui.QWidget(self.frame_optional)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.addSelected = QtGui.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.addSelected.setFont(font)
        self.addSelected.setObjectName(_fromUtf8("addSelected"))
        self.verticalLayout_2.addWidget(self.addSelected)
        self.deleteUnselected = QtGui.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(True)
        self.deleteUnselected.setFont(font)
        self.deleteUnselected.setObjectName(_fromUtf8("deleteUnselected"))
        self.verticalLayout_2.addWidget(self.deleteUnselected)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout.addWidget(self.widget)
        self.listWidget_selected = QtGui.QListWidget(self.frame_optional)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Tahoma"))
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.listWidget_selected.setFont(font)
        self.listWidget_selected.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.listWidget_selected.setObjectName(_fromUtf8("listWidget_selected"))
        self.horizontalLayout.addWidget(self.listWidget_selected)
        self.verticalLayout.addWidget(self.frame_optional)
        self.button_box = QtGui.QDialogButtonBox(OtoklimDialogBase)
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.button_box.setObjectName(_fromUtf8("button_box"))
        self.verticalLayout.addWidget(self.button_box)

        self.retranslateUi(OtoklimDialogBase)
        QtCore.QObject.connect(self.button_box, QtCore.SIGNAL(_fromUtf8("accepted()")), OtoklimDialogBase.accept)
        QtCore.QObject.connect(self.button_box, QtCore.SIGNAL(_fromUtf8("rejected()")), OtoklimDialogBase.reject)
        QtCore.QMetaObject.connectSlotsByName(OtoklimDialogBase)

    def retranslateUi(self, OtoklimDialogBase):
        OtoklimDialogBase.setWindowTitle(_translate("OtoklimDialogBase", "Otoklim", None))
        self.groupBox_1.setTitle(_translate("OtoklimDialogBase", "Determine input Data, Mode And Parameter :", None))
        self.label_8.setText(_translate("OtoklimDialogBase", "*year now by default", None))
        self.label_4.setText(_translate("OtoklimDialogBase", "This Year", None))
        self.mode_1.setText(_translate("OtoklimDialogBase", "Jawa Timur Province Only", None))
        self.label_2.setText(_translate("OtoklimDialogBase", "Choose CSV Delimiter", None))
        self.mode_2.setText(_translate("OtoklimDialogBase", "All Kabupaten Kota", None))
        self.label_6.setText(_translate("OtoklimDialogBase", "Choose Mode :", None))
        self.mode_3.setText(_translate("OtoklimDialogBase", "All Kecamatan", None))
        self.label_7.setText(_translate("OtoklimDialogBase", "*comma by default", None))
        self.label_3.setText(_translate("OtoklimDialogBase", "This Month", None))
        self.mode_4.setText(_translate("OtoklimDialogBase", "Selected Region", None))
        self.label.setText(_translate("OtoklimDialogBase", "Input CH File (CSV)", None))
        self.Browse_CH_CSV.setText(_translate("OtoklimDialogBase", "....", None))
        self.Select_Months.setItemText(0, _translate("OtoklimDialogBase", "Januari", None))
        self.Select_Months.setItemText(1, _translate("OtoklimDialogBase", "Februari", None))
        self.Select_Months.setItemText(2, _translate("OtoklimDialogBase", "Maret", None))
        self.Select_Months.setItemText(3, _translate("OtoklimDialogBase", "April", None))
        self.Select_Months.setItemText(4, _translate("OtoklimDialogBase", "Mei", None))
        self.Select_Months.setItemText(5, _translate("OtoklimDialogBase", "Juni", None))
        self.Select_Months.setItemText(6, _translate("OtoklimDialogBase", "Juli", None))
        self.Select_Months.setItemText(7, _translate("OtoklimDialogBase", "Agustus", None))
        self.Select_Months.setItemText(8, _translate("OtoklimDialogBase", "September", None))
        self.Select_Months.setItemText(9, _translate("OtoklimDialogBase", "Oktober", None))
        self.Select_Months.setItemText(10, _translate("OtoklimDialogBase", "November", None))
        self.Select_Months.setItemText(11, _translate("OtoklimDialogBase", "Desember", None))
        self.addSelected.setText(_translate("OtoklimDialogBase", "+", None))
        self.deleteUnselected.setText(_translate("OtoklimDialogBase", "-", None))

